### ISSUE TITLE
.ics downloads aren't working in Safari

### ISSUE THREAD

**Issue by ndorfin** [Code4SA/taxclock#26]
Hey,

I guess this is more of an FYI than an issue.
I'm using Safari 9.0.3 on Mac OS X 10.11.3. When I click the Download ICS button, Safari pops open a new tab, but nothing is downloaded. I noticed the same behaviour when using ics.js, so the shortcomings are probably due to Safari's handling of Blobs or the download attribute or both.
See a similar issue with ics.js: https://github.com/nwcell/ics.js/issues/27

Might be better to do some feature detection, and then only show the download link if the browser supports blobs or downloads.

Ciao!
-S

**Comment by adieyal** [comment]
Thanks - will have a look

On Tue, Mar 22, 2016 at 11:22 PM, ndorfin notifications@github.com wrote:

> Hey,
> I'm using Safari 9.0.3 on Mac OS X 10.11.3. When I click the Download ICS
> button, Safari pops open a new tab, but nothing is downloaded. I noticed
> the same behaviour when using an ics.js, so the shortcomings are probably
> due to Safari's handling of Blobs or the download attribute or both.
> See a similar issue with ics.js: nwcell/ics.js#27
> https://github.com/nwcell/ics.js/issues/27
> 
> —
> You are receiving this because you are subscribed to this thread.
> Reply to this email directly or view it on GitHub
> https://github.com/Code4SA/taxclock/issues/26

## 

Adi Eyal
Director
Code for South Africa
Promoting informed decision-making

phone: +27 78 014 2469
skype: adieyalcas
linkedin: http://za.linkedin.com/pub/dir/Adi/Eyal
web: http://www.code4sa.org
twitter: @soapsudtycoon

Follow us on twitter at @code4sa
For more information on how to participate in the open data community in
South Africa, go to: http://www.code4sa.org/#community
Sign up for Naked Data, our weekly round-up of what's happening locally and
internationally in data journalism and data visualisation. Register here:
http://www.code4sa.org/newsletter

**Comment by sheva29** [comment]
Ran into the same issues. I wonder if there's a work around?

Thanks!
